### ISSUE TITLE
Change fill based on location certainty

### ISSUE THREAD

**Issue by ebgoldstein** [elsemar/UNPA_AMBR#3]
Do we want to change the fill of the markers (or some other easy to adjust marker parameter) based on if the location is reported vs assigned (during the lit review?).

**Comment by elsemar** [comment]
Th markers are now filled if the lat/long location is specified in the original data.  I aggregated the plantref$selectedbyreader value into the speciesatlocation dataframe and called on it as the fillOpacity value in the addCircleMarkers function.

**Comment by elsemar** [comment]
I created a 'fillvec" analogous to the "spvec" to specify whether the markers should be filled or not.
